---
name: Push to master

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: tetris-build
          path: dist/
          retention-days: 7
          if-no-files-found: error

  deploy:
    name: Deploy to website
    runs-on: ubuntu-latest
    environment: Kapsi
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tetris-build
          path: dist/
      - uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          ARGS: -av --delete-after
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SSH_DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.SSH_DEPLOY_USERNAME }}
          TARGET: ${{ secrets.TETRIS_DEST_DIR }}/
